baseurl: "https://ubnetdef.org/"
languageCode: "en-us"
title: "UBNetDef"
theme: "ubnetdef_2016"
disableHugoGeneratorInject: true

menu:
  main:
    - Name: "about"
      Weight: 100
      URL: "/about"

    - Name: "courses"
      Weight: 200
    - Name: "Systems Security"
      Weight: 201
      URL: "/courses/syssec"
      Parent: "courses"
    - Name: "Network Security"
      Weight: 202
      URL: "/courses/netsec"
      Parent: "courses"
    - Name: "Security Development Program"
      Weight: 203
      URL: "/courses/secdev"
      Parent: "courses"
    - Name: "---"
      Weight: 250
      Parent: "courses"
    - Name: "Systems Security (Fall 2016)"
      Weight: 251
      URL: "/courses/syssec_fa16"
      Parent: "courses"

    - Name: "lectures"
      Weight: 300
      URL: "/lectures"

    - Name: "competitions"
      Weight: 400
    - Name: "Lockdown"
      Weight: 401
      URL: "https://lockdown.ubnetdef.org"
      Parent: "competitions"

    - Name: "wiki"
      Weight: 500
      URL: "https://wiki.ubnetdef.org"
